import type { DataPoint } from "./types";
export declare class BitcoinGraph {
    private width;
    private height;
    private gui;
    private display;
    private left;
    private right;
    private top;
    private bottom;
    private totalPlotPoints;
    currentPlotPoints: DataPoint[];
    private currentScreenPoints;
    private zoom;
    private offsetX;
    private offsetY;
    private xAxis;
    private yAxis;
    private changedPos;
    private changedMouse;
    private clicked;
    private dragging;
    private pointList;
    private lineList;
    private totalDays;
    private maxPrice;
    private minPrice;
    mode: string;
    private tableTitle;
    constructor(width: number, height: number);
    private resetTransforms;
    private addPointsToScreen;
    setPlotPoints(points: DataPoint[]): void;
    setGraphRange(type: string): void;
    private priceToPoint;
    private constrainMouseX;
    private closestPointToMouse;
    private shadeGraphBackground;
    private drawLabels;
    private drawIntersectLines;
    private drawPoints;
    private drawAxes;
    draw(text: string): void;
    drawLive(text: string): void;
    open(mode: string): void;
}
