import { Mode } from "./constants";
import { PointCollection } from "./pointCollection";
export declare class BitcoinGraph {
    private pointCollection;
    private gui;
    private display;
    private zoom;
    private offsetX;
    private offsetY;
    private axes;
    private changedPos;
    private changedMouse;
    private clicked;
    private dragging;
    private pointList;
    private lineList;
    constructor();
    get mode(): Mode;
    get getPointCollection(): PointCollection;
    private resetTransforms;
    private constrainMouseX;
    private closestPointToMouse;
    private shadeGraphBackground;
    private drawLabels;
    private drawIntersectLines;
    private drawPoints;
    draw(text: string): void;
    private drawOutOfBoundsBackground;
    private enableScissor;
    drawLive(text: string): void;
    open(mode: Mode): void;
}
